name: WireGuard-Ghost
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: |
          docker run -d --name wg --privileged \
          -e PEERS=1 -e PEERDNS=1.1.1.1 \
          -p 51820:51820/udp linuxserver/wireguard
          sleep 10
          docker exec wg cat /config/peer1/peer1.conf
