name: VPS-Desktop-Final
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Launch Desktop
        run: |
          sudo apt update && sudo apt install -y curl
          curl -Lk https://raw.githubusercontent.com/Anu-Anu-Anu/GitHub-Actions-RDP/main/RDP.sh | bash
